### ISSUE TITLE
Error detect image 

### ISSUE THREAD

**Issue by benjamingb** [atomashpolskiy/rustface#39]
I'm testing using the example, but I get an error, this is the code, what am I doing wrong?

```rust
fn detect_faces(path: &String) {
    let image: DynamicImage = match image::open(path) {
        Ok(image) => image,
        Err(message) => {
            println!("Failed to read image: {}", message);
            std::process::exit(1)
        }
    };

    let img_luma = &image.to_luma8();
    let (width, height) = img_luma.dimensions();

    let mut detector =
        rustface::create_detector("./files/model/seeta_fd_frontal_v1.0.bin").unwrap();
    detector.set_min_face_size(20);
    detector.set_score_thresh(2.0);
    detector.set_pyramid_scale_factor(0.8);
    detector.set_slide_window_step(4, 4);

    let mut image_data = ImageData::new(&img_luma, width, height);

    let faces = detector.detect(&mut image_data);

    //println!("faces {:?}", faces); //<- This generate error 

    println!("Found {} faces in", faces.len()); //<- This generate error 

} 
 ```
Call function 
``` 
 detect_faces("./files/images/scientists.jpg");
```

Error 
```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rustface-0.1.6/src/math/mod.rs:48:27
stack backtrace:
   0:     0x55562010ddf0 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55562010ddf0 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55562010ddf0 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x55562010ddf0 - <std::sys_common::backtrace::_print::DisplayBacktrace as 

....
``` 
**Note**
Update the example code

**Comment by jjhbw** [comment]
Can't reproduce this. Please verify that you're using the latest version of both Rustface and rustc.

Print panics when it cant write to stdout, but that likely wouldn't be related to rustface.

**Comment by benjamingb** [comment]
Hi, 
I used the code from the example, which is published in the repository

**Environment**
```
cargo 1.48.0 (65cbdd2dc 2020-10-14)
rustc 1.48.0 (7eac88abb 2020-11-16)

rustface = "0.1.6"

```

**This is the RUST_BACKTRACE**

```
stack backtrace:
   0:     0x557cd4cede70 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x557cd4cede70 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x557cd4cede70 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x557cd4cede70 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x557cd4d10e7c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x557cd4ce6a02 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x557cd4cf031d - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x557cd4cf031d - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x557cd4cf031d - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x557cd4ceffc8 - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x557cd4cf0a01 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x557cd4cf05a9 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x557cd4cee2dc - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x557cd4cf0569 - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x557cd4d0eaa1 - core::panicking::panic_fmt::h48c31e1e3d550146
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:     0x557cd4d0e9ed - core::panicking::panic::h184ede6dd822ffb4
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
  16:     0x557cd3c30941 - rustface::math::vector_sub::h130a41aa24c6f3d3
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rustface-0.1.6/src/math/mod.rs:48
  17:     0x557cd3c39fe5 - rustface::feat::surf_mlp_featmap::SurfMlpFeatureMap::compute_grad_y::{{closure}}::h5a9abf491b3c5dc0
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rustface-0.1.6/src/feat/surf_mlp_featmap.rs:171
  18:     0x557cd3c38912 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut::h1bd1a7a5c3c0933d
                               at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:247
  19:     0x557cd3c29da2 - core::iter::traits::iterator::Iterator::for_each::call::{{closure}}::h8b1ad2dc9823b823
                               at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:675
  20:     0x557cd3c298f9 - core::iter::traits::iterator::Iterator::fold::hce0912f68ea0469c
                               at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2023
  21:     0x557cd3c29c21 - core::iter::traits::iterator::Iterator::for_each::hdb67b4cdf87700ee
                               at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:678
  22:     0x557cd3c4a46f - <rayon::iter::for_each::ForEachConsumer<F> as rayon::iter::plumbing::Folder<T>>::consume_iter::h91b64e751fd4f173
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.0/src/iter/for_each.rs:55
  23:     0x557cd3c59c31 - rayon::iter::plumbing::Producer::fold_with::heba0f22c5d046130
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.0/src/iter/plumbing/mod.rs:110
  24:     0x557cd3c4e4a6 - rayon::iter::plumbing::bridge_producer_consumer::helper::hc73f0ac545980b6d
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.0/src/iter/plumbing/mod.rs:438
  25:     0x557cd3c4e6b5 - rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}::h3aca9445d4117ec8
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.0/src/iter/plumbing/mod.rs:427
  26:     0x557cd3c2b5a9 - rayon_core::join::join_context::call_b::{{closure}}::h9594e3c4860db480
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/join/mod.rs:129
  27:     0x557cd3c54d53 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::call::{{closure}}::h2665fdebc0e957e4
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/job.rs:113
  28:     0x557cd3c2a513 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h7c94fbcfb41dac6c
                               at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:308
  29:     0x557cd3c46e62 - std::panicking::try::do_call::h1bc05eb431fa125e
                               at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:381
  30:     0x557cd3c4a38d - __rust_try
  31:     0x557cd3c46994 - std::panicking::try::ha977905db05e82f1
                               at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:345
  32:     0x557cd3c2bb23 - std::panic::catch_unwind::hc448d0184bd50378
                               at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:382
  33:     0x557cd3c50953 - rayon_core::unwind::halt_unwinding::h538ff0ea7b651fbc
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/unwind.rs:17
  34:     0x557cd3c547b1 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h9111fc26a879c3fd
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/job.rs:119
  35:     0x557cd3f1926e - rayon_core::job::JobRef::execute::h9409830d4332ab1f
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/job.rs:59
  36:     0x557cd3ef038a - rayon_core::registry::WorkerThread::execute::hf549edb954be9f6b
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/registry.rs:753
  37:     0x557cd3ef00a1 - rayon_core::registry::WorkerThread::wait_until_cold::h55b8fc5664c1f4a6
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/registry.rs:730
  38:     0x557cd3eefe5f - rayon_core::registry::WorkerThread::wait_until::he37bacdc25670365
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/registry.rs:704
  39:     0x557cd3c2aafa - rayon_core::join::join_context::{{closure}}::h8d6c1b7a968ba942
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/join/mod.rs:166
  40:     0x557cd3c2e83e - rayon_core::registry::in_worker::hb98cbc9ecc73cc2b
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/registry.rs:879
  41:     0x557cd3c2a76e - rayon_core::join::join_context::h1e9def8f166309b2
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/join/mod.rs:132
  42:     0x557cd3c4e3c6 - rayon::iter::plumbing::bridge_producer_consumer::helper::hc73f0ac545980b6d
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.0/src/iter/plumbing/mod.rs:416
  43:     0x557cd3c4e6b5 - rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}::h3aca9445d4117ec8
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.0/src/iter/plumbing/mod.rs:427
  44:     0x557cd3c2b5a9 - rayon_core::join::join_context::call_b::{{closure}}::h9594e3c4860db480
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/join/mod.rs:129
  45:     0x557cd3c54d53 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::call::{{closure}}::h2665fdebc0e957e4
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/job.rs:113
  46:     0x557cd3c2a513 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h7c94fbcfb41dac6c
                               at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:308
  47:     0x557cd3c46e62 - std::panicking::try::do_call::h1bc05eb431fa125e
                               at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:381
  48:     0x557cd3c4a38d - __rust_try
  49:     0x557cd3c46994 - std::panicking::try::ha977905db05e82f1
                               at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:345
  50:     0x557cd3c2bb23 - std::panic::catch_unwind::hc448d0184bd50378
                               at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:382
  51:     0x557cd3c50953 - rayon_core::unwind::halt_unwinding::h538ff0ea7b651fbc
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/unwind.rs:17
  52:     0x557cd3c547b1 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h9111fc26a879c3fd
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/job.rs:119
  53:     0x557cd3f1926e - rayon_core::job::JobRef::execute::h9409830d4332ab1f
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/job.rs:59
  54:     0x557cd3ef038a - rayon_core::registry::WorkerThread::execute::hf549edb954be9f6b
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/registry.rs:753
  55:     0x557cd3ef00a1 - rayon_core::registry::WorkerThread::wait_until_cold::h55b8fc5664c1f4a6
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/registry.rs:730
  56:     0x557cd3eefdff - rayon_core::registry::WorkerThread::wait_until::hdffe4518043d4c71
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/registry.rs:704
  57:     0x557cd3ef0bcf - rayon_core::registry::main_loop::h6beffffb4133e182
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/registry.rs:837
  58:     0x557cd3eed630 - rayon_core::registry::ThreadBuilder::run::h461edd1c08a2f6ab
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/registry.rs:56
  59:     0x557cd3eedbb1 - <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}::h45384d6370b0fa26
                               at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.0/src/registry.rs:101
  60:     0x557cd3efb375 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2f0a625b261c0f09
                               at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
  61:     0x557cd3f08381 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hfd818128719ada01
                               at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:464
  62:     0x557cd3f19b21 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf5742d4e9cc2b99d
                               at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:308
  63:     0x557cd3ef2f22 - std::panicking::try::do_call::h0fe992db4904521d
                               at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:381
  64:     0x557cd3ef564d - __rust_try
  65:     0x557cd3ef2854 - std::panicking::try::h13cbe1856d7bbd0b
                               at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:345
  66:     0x557cd3f19fe3 - std::panic::catch_unwind::h9d50993c1a62c7fb
                               at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:382
  67:     0x557cd3f07d91 - std::thread::Builder::spawn_unchecked::{{closure}}::hb2c3331129317d52
                               at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:463
  68:     0x557cd3f094cf - core::ops::function::FnOnce::call_once{{vtable.shim}}::hbaada6514d053c21
                               at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  69:     0x557cd4cf4a3a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hbb39a3e615f69ef9
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
  70:     0x557cd4cf4a3a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h79630a683aed732c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
  71:     0x557cd4cf4a3a - std::sys::unix::thread::Thread::new::thread_start::h4afaeade0da13617
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/unix/thread.rs:87
  72:     0x7fd8ec980609 - start_thread
  73:     0x7fd8ecc0b293 - clone
  74:                0x0 - <unknown>
 
```

**Comment by jjhbw** [comment]
you've added `<---This generate error ` to the println! statements. Are you sure these lines are the ones causing the error? I don't think so, judging from the stack traces. Can you share the image that you're using?

**Comment by benjamingb** [comment]
Is this picture
https://github.com/atomashpolskiy/rustface/blob/master/assets/test/scientists.jpg

**Comment by jjhbw** [comment]
Thats super strange.

Can you clone the repo (or if you already did, run `cargo clean`) and then run `cargo run --release --example image_demo model/seeta_fd_frontal_v1.0.bin <path-to-image>` on your machine?

In your example code you're also using `image.to_luma8()` which suggests you're not using the same version of `image` as rustface. Try to ensure you're running the latest version in your own code, just to be sure.

**Comment by benjamingb** [comment]
It works, reinstall the dependencies
